name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake ..
        working-directory: build

      - name: Run make
        run: make
        working-directory: build
